### ISSUE TITLE
JavaFX Class Not Found

### ISSUE THREAD

**Issue by Sukasa** [Col-E/Recaf-Launcher#12]
Downloaded launcher 0.4.0, downloaded Java 22 x64 and installed that ahead of time.  When I try to run recaf via the launcher, it downloads recaf and JavaFX, however there seems to be a class required that is not available.

```
 - java.version = 22.0.1
 - java.vm.vendor = Oracle Corporation
 - java.vm.version = 22.0.1+8-16
...
Running Recaf '4.0.0-SNAPSHOT' with JavaFX '23-ea+3:win'
08:34:52.540 [JFXValidation/main] ERROR: JFX validation failed, could not find 'VersionInfo' class
java.lang.ClassNotFoundException: com.sun.javafx.runtime.VersionInfo
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:413)
        at java.base/java.lang.Class.forName(Class.java:404)
        at software.coley.recaf.util.JFXValidation.validateJFX(JFXValidation.java:33)
        at software.coley.recaf.Main.main(Main.java:70)```

**Comment by Col-E** [comment]
I typo'd `>` where it shoulda been a `<` - Update to `0.4.1`
