### ISSUE TITLE
Crashing on start recaf

### ISSUE THREAD

**Issue by MatrixAura** [Col-E/Recaf-Launcher#24]
here is logs:
```
Looking in 'C:\Users\******\AppData\Roaming\Recaf' for Recaf/dependencies...
Attempting to resolve JFX version in current classpath...
No JavaFX version class found in the current classpath
Running Recaf '4.0.0-SNAPSHOT' with JavaFX '24-ea+5:win'
16:59:47.223 [AccessPatcher/main] DEBUG: Opening access to all packages
16:59:47.241 [AccessPatcher/main] DEBUG: Patching package reflection restrictions
16:59:47.286 [JFXValidation/main] INFO : JavaFX successfully initialized: 24-ea
16:59:47.287 [Bootstrap/main] INFO : Initializing Recaf 4.0.0-SNAPSHOT
 - Build rev:  1
 - Build date: 2024 08/18 06:45
 - Build hash: 27a3a98f9c02e2abdcbfeb8af11f2f3e406a28bc
16:59:47.288 [Bootstrap/main] INFO : Creating Recaf CDI container...
16:59:47.291 [Bootstrap/main] INFO : CDI: Adding interceptors & extensions
16:59:47.293 [Bootstrap/main] INFO : CDI: Registering bean packages
16:59:47.294 [Bootstrap/main] INFO : CDI: Running user-defined Consumer<Weld>
16:59:47.294 [Bootstrap/main] INFO : CDI: Initializing...
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type BundleIconProviderFactory with qualifiers @Default
  at injection point [BackedAnnotatedParameter] Parameter 14 of [BackedAnnotatedConstructor] @Inject public software.coley.recaf.services.cell.icon.IconProviderService(@Nonnull IconProviderServiceConfig, @Nonnull ClassIconProviderFactory, @Nonnull FileIconProviderFactory, @Nonnull InnerClassIconProviderFactory, @Nonnull FieldIconProviderFactory, @Nonnull MethodIconProviderFactory, @Nonnull InstructionIconProviderFactory, @Nonnull ThrowsIconProviderFactory, @Nonnull CatchIconProviderFactory, @Nonnull VariableIconProviderFactory, @Nonnull AnnotationIconProviderFactory, @Nonnull PackageIconProviderFactory, @Nonnull DirectoryIconProviderFactory, @Nonnull BundleIconProviderFactory, @Nonnull ResourceIconProviderFactory)
  at software.coley.recaf.services.cell.icon.IconProviderService.<init>(IconProviderService.java:0)

        at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:382)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:297)
        at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:144)
        at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:166)
        at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:537)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:65)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:63)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
        at org.jboss.weld.executor.CommonForkJoinPoolExecutorServices.lambda$wrap$0(CommonForkJoinPoolExecutorServices.java:70)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedInterruptibleCallable.compute(ForkJoinTask.java:1689)
        at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by Col-E** [comment]
What happens if you delete `C:\Users\******\AppData\Roaming\Recaf\dependencies` and try again?

**Comment by MatrixAura** [comment]
I don't know why I can't recover this error now. But now there is another abnormality:
```
08:58:06.834 [Main/JavaFX Application Thread] ERROR: Uncaught exception on thread 'JavaFX Application Thread'
jakarta.enterprise.inject.CreationException: null
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:132)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:259)
        at java.base/java.lang.Class.newInstance(Class.java:755)
        at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:50)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:90)
        at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:131)
        at org.jboss.weld.injection.ConstructorInjectionPoint.invokeAroundConstructCallbacks(ConstructorInjectionPoint.java:95)
        at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:81)
        at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:121)
        at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:197)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:164)
        at org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:64)
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:104)
        at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:723)
        at org.jboss.weld.bean.builtin.InstanceImpl.getBeanInstance(InstanceImpl.java:267)
        at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:116)
        at software.coley.recaf.ui.pane.editing.assembler.AssemblerToolTabs.createChildren(AssemblerToolTabs.java:78)
        at software.coley.recaf.ui.pane.editing.assembler.AssemblerToolTabs.onUpdatePath(AssemblerToolTabs.java:127)
        at software.coley.recaf.ui.pane.editing.assembler.AssemblerPane.lateInitForMethod(AssemblerPane.java:212)
        at software.coley.recaf.ui.pane.editing.assembler.AssemblerPane.onUpdatePath(AssemblerPane.java:280)
        at software.coley.recaf.services.navigation.Actions.lambda$openAssembler$47(Actions.java:1568)
        at software.coley.recaf.services.navigation.Actions.createContent(Actions.java:2161)
        at software.coley.recaf.services.navigation.Actions.openAssembler(Actions.java:1556)
        at software.coley.recaf.services.navigation.Actions$Proxy$_$$_WeldClientProxy.openAssembler(Unknown Source)
        at software.coley.recaf.services.cell.context.BasicMethodContextMenuProviderFactory.lambda$getMethodContextMenuProvider$1(BasicMethodContextMenuProviderFactory.java:79)
        at software.coley.collections.func.UncheckedRunnable.run(UncheckedRunnable.java:15)
        at software.coley.recaf.ui.control.ActionMenuItem.lambda$new$1(ActionMenuItem.java:61)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
        at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
        at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3894)
        at javafx.scene.Scene.processMouseEvent(Scene.java:1887)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2620)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.NoSuchFieldError: Class javafx.scene.control.TableView does not have member field 'javafx.util.Callback CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN'
        at software.coley.recaf.ui.pane.editing.assembler.JvmStackAnalysisPane.<init>(JvmStackAnalysisPane.java:77)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:123)
        ... 64 common frames omitted
Weld SE container recaf shut down by shutdown hook
```
Maybe should I update my JavaFx?

**Comment by MatrixAura** [comment]
It's back to normal now.

**Comment by Col-E** [comment]
I see this randomly happen to users but I have no idea why its bugging out randomly. I cannot ever reproduce the issue :/
