### ISSUE TITLE
unable to update jfx 

### ISSUE THREAD

**Issue by Memexurer** [Col-E/Recaf-Launcher#3]
`dependencies` folder in appdata\recaf isnt created automatically :(((

```
Failed downloading FX artifact: ' https://repo1.maven.org/maven2/org/openjfx/javafx-media/22-ea+16/javafx-media-22-ea+16-win.jar'
java.nio.file.NoSuchFileException: C:\Users\yeah\AppData\Roaming\Recaf\dependencies\javafx-media-22-ea+16-win.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.copy(Unknown Source)
        at software.coley.recaf.launch.commands.UpdateJavaFX.updateTo(UpdateJavaFX.java:200)
        at software.coley.recaf.launch.commands.UpdateJavaFX.update(UpdateJavaFX.java:159)
        at software.coley.recaf.launch.commands.UpdateJavaFX.call(UpdateJavaFX.java:44)
        at software.coley.recaf.launch.commands.UpdateJavaFX.call(UpdateJavaFX.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at software.coley.recaf.launch.Launcher.main(Launcher.java:51)
        ```

**Comment by Col-E** [comment]
Whoops, [fixed](https://github.com/Col-E/Recaf-Launcher/commit/3007c35714c63bc77907d00eb846ac0e7d955aa0)
