### ISSUE TITLE
failed to fetch dependencies

### ISSUE THREAD

**Issue by neilhuang007** [Col-E/Recaf-Launcher#5]
runed java -jar <jar> update-jfx
and the following error appeared
`java.nio.file.NoSuchFileException: C:\Users\neilhuang007\AppData\Roaming\Recaf\dependencies
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:541)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:481)
        at java.base/java.nio.file.Files.list(Files.java:3767)
        at software.coley.recaf.launch.info.JavaFxVersion.getLocalVersion(JavaFxVersion.java:66)
        at software.coley.recaf.launch.commands.UpdateJavaFX.update(UpdateJavaFX.java:153)
        at software.coley.recaf.launch.commands.UpdateJavaFX.call(UpdateJavaFX.java:44)
        at software.coley.recaf.launch.commands.UpdateJavaFX.call(UpdateJavaFX.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at software.coley.recaf.launch.Launcher.main(Launcher.java:51)`

**Comment by Col-E** [comment]
Need to first check if the dir exists 🤦 

https://github.com/Col-E/Recaf-Launcher/blob/master/src/main/java/software/coley/recaf/launch/info/JavaFxVersion.java#L66

**Comment by Col-E** [comment]
7d4001f93e98fbe756b4995d67c1834a6fae8388
